CREATE DATABASE library_lab;
USE library_lab;

CREATE TABLE MEMBER(
MemberID INT PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Age INT CHECK(Age>=12),
Gender ENUM('MALE','FEMALE','OTHER')
);

CREATE TABLE BOOK(
BookID INT PRIMARY KEY,
Title VARCHAR(150) NOT NULL,
ISBN VARCHAR(20) NOT NULL UNIQUE,
Price DECIMAL(6,2) CHECK(Price>=0),
Status ENUM('AVAILABLE','BORROWED') DEFAULT 'AVAILABLE'
);

CREATE TABLE LOAN(
LoanID INT PRIMARY KEY,
MemberID INT,
BookID INT,
FOREIGN KEY(MemberID) REFERENCES MEMBER(MemberID),
FOREIGN KEY(BookID) REFERENCES BOOK(BookID)
);

INSERT INTO MEMBER
VALUES
(1,"Ariful Hasan","ariful@gmail.com",22,"MALE"),
(2,"Nusrat Jahan","nusrat@gmail.com",20,"FEMALE"),
(3,"Rahim Uddin","rahim@gmail.com",25,"MALE"),
(4,"Karim Ali","karim@gmail.com",30,"MALE"),
(5,"Sadia Islam","sadia@gmail.com",19,"FEMALE");

INSERT INTO BOOK
VALUES
(101,"Database Systems","ISBN001",450.00,"AVAILABLE"),
(102,"C Programming","ISBN002",350.00,"AVAILABLE"),
(103,"Data Structures","ISBN003",500.00,"AVAILABLE"),
(104,"Operating Systems","ISBN004",600.00,"AVAILABLE"),
(105,"Computer Networks","ISBN005",550.00,"AVAILABLE");

INSERT INTO LOAN
VALUES
(1,1,101),
(2,2,102),
(3,3,103),
(4,4,104),
(5,5,105),
(6,1,102);
